language: node_js

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: scFqsC1gDFHj9/K31IzUzNv6jrx4ZtpaQ7HCQh81Ho5sYG1EfWKBaWTer5ey6aC277DwtncO2soNnwtiSsoEm0y6x2E+vtpLc/NHQjBVF0QpaMjtvvjnRgyZzDoJbag7eBHnDLHBwXCqANcSSJCBtKT4I6X8pyfrcYTsx5yIJK6nVwTXH64x04SxdhtP3UU4atw3JlkCVpdh8mqfH1cM5ryBgigKFkbDg8zKR7z2jV9rI/mIRjjQKB8ZLY3Wm7s4X2JmuyGBnqKvKHmjJVqX0ecUf2um4I/E8z/u14oYLvgjZ/sZF/ILHY+cO4ct8JxykFya25xsT3TzxeMZ8cmaMBYzn5paz/4DYseOQs8wXp6FSFgK1v3xH2aHJlSQXGGsLwRByPARmT6H7uFUbW9kcaeV9KJmJfqSgmFfp2FyVFRGWspOHLbkNe0sNx/nYoGKQr+iFqsDrQOh8zl+l95N7fkvnU8uTtc9NOR9N1MTmQ7y/kBiXHNM+ZCtNTw8qxjc49KVxBjSuH+fkkLrobipZnEmNhQ4QSlhagfqeuHoK+14zM/Fi00d/JI3yDYd9ub+V+lD1VRCi1/s60LORVvEwFir2GzOSNRJonXdZC195+r40Fdb4QG2wLZkJbWNbdBS+YjaeXDbaV+IK2cSHmUdAA+hxoANu6EDzd1/x9QcxcI=

branches:
  only:
  - master
  - "/^v[0-9\\.]+/"

cache:
  directories:
    - "${HOME}/.composer/cache"
    - "${TRAVIS_BUILD_DIR}/.work"

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: test
    if: branch = master and tag IS blank and type IN (pull_request, api)
  - name: update
    if: branch = master and tag IS blank and type IN (api, cron)
  - name: deploy
    if: tag IS present

before_install:
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Update" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Deploy" ]]; then openssl aes-256-cbc -K $encrypted_fea3c3191547_key -iv $encrypted_fea3c3191547_iv -in ./id_rsa.enc -out ~/.ssh/id_rsa -d 2>/dev/null; fi
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Update" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Deploy" ]]; then chmod 600 ~/.ssh/id_rsa; fi
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Update" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Deploy" ]]; then echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config; fi
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Update" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Deploy" ]]; then git config --global user.email "technote.space@gmail.com"; fi
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Update" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Deploy" ]]; then git config --global user.name "Technote"; fi
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Update" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Deploy" ]]; then git config --global url."git@github.com:".insteadOf "https://github.com/"; fi
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Check" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Test" ]]; then git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci; fi
  - if [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Check" ]] || [[ "${TRAVIS_BUILD_STAGE_NAME}" == "Test" ]]; then bash travis-ci/bin/prepare.sh install; fi

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh


    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - ACTIVATE_POPULAR_PLUGINS=1
        - ACTIVATE_GUTENBERG=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.0'
      env: WP_VERSION=5.0
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
        - ACTIVATE_GUTENBERG=1
        - COVERAGE_REPORT=1
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=4.9
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=3.9
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.3'
      env: WP_VERSION=trunk
      script: bash travis-ci/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=trunk
      script: bash travis-ci/bin/php/wp-test.sh


    - stage: update
      language: node_js
      node_js: '11'
      script: bash bin/update.sh


    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      before_deploy:
        - source bin/deploy/env.sh
        - bash bin/deploy/create-zip.sh
      deploy:
        provider: releases
        skip_cleanup: true
        name: ${RELEASE_TITLE}
        tag_name: ${RELEASE_TAG}
        api_key:
          secure: ij6EEfS2oV3dnH8ylMaV3AWUnwqQRFAYL6HeC5+EGYjh/EoB6+cTOVfjX5qrTpRzIz1PdsKQaws5DET26uRDVQIGiySL1RaTZ9zoiCe1uwllZ3gXtHaiiEL5oZSz4bjpww1kqbXANGUOlz9Mnkk+9c0ogtpiBSfIVhMshGN2OKwNDPdgwE27aW3d1ccUHpgs52b5lD01B53hZUxtoiyEcoIBGYSL5xLOVNh626j0ViNhlkjQEAS7STV5LSRVDwXEYZB6nsR8nag59BSOf5y33TYCiGFdlkV3H+3xki/Lgrw+ZY0urCcM9s2J7lkxMqnkXKV64sWUmORsY+6ZyskAbO4RFMFQgtxWPuJyy8kSGIpW2yJxztHMNvPbPzG9x+8IAh1yWuX9dgV2Y8CVq4hi36M8Qk5+CWX3xooYIXU/NiKX8niMSWmmzj2cWlq3KO3UGy8/dsTBzOwLliHR2CkPMDvbDJC/s+BeBQ3dOpT3cEMCkV7ceS0AuXL4LXtreB99VYmOguOtlK5XzmDr6EwCMg99hr5okBQljN+hJIxJj2axRCn8rGm2Y5Do2/ogcQ46gmpKVRb21xXuSHloYYgPIdHZUbebtdRSXyHGqohV7jpsuJ3odNUdXigujnOI2NMdlw9aLN773h+ROgxw6mterz8NDs03KlTvcPeVcxjOCe8=
        file:
          - ${RELEASE_FILE}
        body: ${RELEASE_BODY}
        overwrite: true
        on:
          tags: true

    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bash bin/deploy/gh-pages.sh
        on:
          tags: true

  allow_failures:
    - env: WP_VERSION=4.9
    - env: WP_VERSION=3.9
    - env: WP_VERSION=trunk
