language: node_js

sudo: false
dist: trusty

git:
  depth: 3

branches:
  only:
  - master
  - "/^v[0-9\\.]+/"

cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/.work"

stages:
- name: update
  if: branch = master and tag IS blank and type IN (api, cron)
- name: deploy
  if: tag IS present

before_install:
  - openssl aes-256-cbc -K $encrypted_fea3c3191547_key -iv $encrypted_fea3c3191547_iv -in ./id_rsa.enc -out ~/.ssh/id_rsa -d 2>/dev/null
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "technote.space@gmail.com"
  - git config --global user.name "Technote"
  - git config --global url."git@github.com:".insteadOf "https://github.com/"

jobs:
  fast_finish: true
  include:
  - stage: update
    language: node_js
    node_js: '11'
    script: bash bin/update.sh

  - stage: deploy
    language: node_js
    node_js: '11'
    dist: trusty
    script: skip
    before_deploy:
      - source bin/deploy/env.sh
      - bash bin/deploy.sh
    deploy:
      provider: releases
      skip_cleanup: true
      name: ${RELEASE_TITLE}
      tag_name: ${RELEASE_TAG}
      api_key:
        secure: ij6EEfS2oV3dnH8ylMaV3AWUnwqQRFAYL6HeC5+EGYjh/EoB6+cTOVfjX5qrTpRzIz1PdsKQaws5DET26uRDVQIGiySL1RaTZ9zoiCe1uwllZ3gXtHaiiEL5oZSz4bjpww1kqbXANGUOlz9Mnkk+9c0ogtpiBSfIVhMshGN2OKwNDPdgwE27aW3d1ccUHpgs52b5lD01B53hZUxtoiyEcoIBGYSL5xLOVNh626j0ViNhlkjQEAS7STV5LSRVDwXEYZB6nsR8nag59BSOf5y33TYCiGFdlkV3H+3xki/Lgrw+ZY0urCcM9s2J7lkxMqnkXKV64sWUmORsY+6ZyskAbO4RFMFQgtxWPuJyy8kSGIpW2yJxztHMNvPbPzG9x+8IAh1yWuX9dgV2Y8CVq4hi36M8Qk5+CWX3xooYIXU/NiKX8niMSWmmzj2cWlq3KO3UGy8/dsTBzOwLliHR2CkPMDvbDJC/s+BeBQ3dOpT3cEMCkV7ceS0AuXL4LXtreB99VYmOguOtlK5XzmDr6EwCMg99hr5okBQljN+hJIxJj2axRCn8rGm2Y5Do2/ogcQ46gmpKVRb21xXuSHloYYgPIdHZUbebtdRSXyHGqohV7jpsuJ3odNUdXigujnOI2NMdlw9aLN773h+ROgxw6mterz8NDs03KlTvcPeVcxjOCe8=
      file:
        - ${RELEASE_FILE1}
        - ${RELEASE_FILE2}
      body: ${RELEASE_BODY}
      overwrite: true
      on:
        tags: true
