language: node_js

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: scFqsC1gDFHj9/K31IzUzNv6jrx4ZtpaQ7HCQh81Ho5sYG1EfWKBaWTer5ey6aC277DwtncO2soNnwtiSsoEm0y6x2E+vtpLc/NHQjBVF0QpaMjtvvjnRgyZzDoJbag7eBHnDLHBwXCqANcSSJCBtKT4I6X8pyfrcYTsx5yIJK6nVwTXH64x04SxdhtP3UU4atw3JlkCVpdh8mqfH1cM5ryBgigKFkbDg8zKR7z2jV9rI/mIRjjQKB8ZLY3Wm7s4X2JmuyGBnqKvKHmjJVqX0ecUf2um4I/E8z/u14oYLvgjZ/sZF/ILHY+cO4ct8JxykFya25xsT3TzxeMZ8cmaMBYzn5paz/4DYseOQs8wXp6FSFgK1v3xH2aHJlSQXGGsLwRByPARmT6H7uFUbW9kcaeV9KJmJfqSgmFfp2FyVFRGWspOHLbkNe0sNx/nYoGKQr+iFqsDrQOh8zl+l95N7fkvnU8uTtc9NOR9N1MTmQ7y/kBiXHNM+ZCtNTw8qxjc49KVxBjSuH+fkkLrobipZnEmNhQ4QSlhagfqeuHoK+14zM/Fi00d/JI3yDYd9ub+V+lD1VRCi1/s60LORVvEwFir2GzOSNRJonXdZC195+r40Fdb4QG2wLZkJbWNbdBS+YjaeXDbaV+IK2cSHmUdAA+hxoANu6EDzd1/x9QcxcI=

branches:
  only:
  - master
  - "/^v[0-9\\.]+/"

cache:
  directories:
    - "${HOME}/.composer/cache"
    - "${TRAVIS_BUILD_DIR}/.work"
    - "${TRAVIS_BUILD_DIR}/.plugin"

stages:
  - name: update
    if: branch = master and tag IS blank and type IN (api, cron)

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - git config --global user.email "technote.space@gmail.com"
  - git config --global user.name "Technote"
  - git remote remove origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git


jobs:
  fast_finish: true
  include:
    - stage: update
      language: node_js
      node_js: '11'
      script: bash bin/update.sh
      env:
        - secure: "iU5s5iPxsRTY4eHBjH/1x/nRZiMeMXu7MVexA/mFGAwI7n1JjJPW7v2AmUEkwsAyD55PVly0AVU3v16b//Z5pA8u096VE6+7va1luAclAMojs9NP/WNYiLJbRVWNvswkSCxRE0imNgkir8V+REjpk7YtmbFpp95Ft4RM/YizanK1R2kTCta4g8T5A6YJM/6sEu8GQxH50bF5LVDPznfWTn8zuwP44g8qpFGR0N+srprxkWDkKh9qXk04B/7uBj3y4wRLO7/E50PyDTAQJVqOeBDqY/PkrAVSFQUF9TANpeyApQDY2lvbwDj7HN75MWNoo0lsibGVosdDn5B6rqIS4Scv1vd6Q/cM5ymGAPTwUFFfH4KFAAHIQarU7rqjUsEE9Gh+2ZvbFWc1NY8wyEx4YDdxJjyGvhIZu83hqrXW9vD+kZBjPCAS4O0Q/ck58FOWD1ZLMS2/gDbpt3n4UIG/U0yGkRqGYmpp4GCBcuftAx1HJo1Nz1X0sV8V5CnURLNN4ccXWoG2GFwlrElpWhfeZEqrLfoGi7v5EgBlzl8PKg46KOYhHujxJxistTO5c6jwA+XlZydiV61GY7gLUhFWZphlXXJyYZUnKnz7n9GEEzf/oodtsQZkFrd8gZvrHQEwL9IAuu3tuKGD6ReNDvvANzQKbn3LlxfJ/Dqi22zX6m4="

    - stage: deploy
      language: node_js
      node_js: '11'
      dist: trusty
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: bash bin/deploy/gh-pages.sh
        on:
          tags: true
      env:
        - secure: "iU5s5iPxsRTY4eHBjH/1x/nRZiMeMXu7MVexA/mFGAwI7n1JjJPW7v2AmUEkwsAyD55PVly0AVU3v16b//Z5pA8u096VE6+7va1luAclAMojs9NP/WNYiLJbRVWNvswkSCxRE0imNgkir8V+REjpk7YtmbFpp95Ft4RM/YizanK1R2kTCta4g8T5A6YJM/6sEu8GQxH50bF5LVDPznfWTn8zuwP44g8qpFGR0N+srprxkWDkKh9qXk04B/7uBj3y4wRLO7/E50PyDTAQJVqOeBDqY/PkrAVSFQUF9TANpeyApQDY2lvbwDj7HN75MWNoo0lsibGVosdDn5B6rqIS4Scv1vd6Q/cM5ymGAPTwUFFfH4KFAAHIQarU7rqjUsEE9Gh+2ZvbFWc1NY8wyEx4YDdxJjyGvhIZu83hqrXW9vD+kZBjPCAS4O0Q/ck58FOWD1ZLMS2/gDbpt3n4UIG/U0yGkRqGYmpp4GCBcuftAx1HJo1Nz1X0sV8V5CnURLNN4ccXWoG2GFwlrElpWhfeZEqrLfoGi7v5EgBlzl8PKg46KOYhHujxJxistTO5c6jwA+XlZydiV61GY7gLUhFWZphlXXJyYZUnKnz7n9GEEzf/oodtsQZkFrd8gZvrHQEwL9IAuu3tuKGD6ReNDvvANzQKbn3LlxfJ/Dqi22zX6m4="
