on:
  schedule:
    - cron: 32 20 * * *
  repository_dispatch:
    types: [update-deps]
  workflow_dispatch:

name: Update dependencies

env:
  GITHUB_ACTION: 1
  TRAVIS_BUILD_DIR: ${{ github.workspace }}

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Prepare setting
        run: git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
      - name: Get new tag
        run: echo "NEXT_TAG=$(bash travis-ci/bin/update/commit/get-new-tag.sh)" >> $GITHUB_ENV
      - run: bash bin/update.sh
      - uses: EndBug/add-and-commit@v5
        with:
          add: 'data'
          message: 'feat: update version data'
          tag: ${{ env.NEXT_TAG }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
